### ISSUE TITLE
浓烈的慕课Spring Security实战课风格哈哈哈

### ISSUE THREAD

**Issue by Parker1995** [momokanni/security-wrapper#1]
那个OAuth2实战链接废了

**Comment by momokanni** [comment]
基于那个不假，但是有延伸，并不一样

**Comment by momokanni** [comment]
OAuth2是自己归纳的OAuth2的授权类型

**Comment by momokanni** [comment]
确实基于那个，但绝对和那个不一样，举一个例：关于security && oauth2的坑，除了它们各自官方issue有提及外，也就只有我这有解决方案。
另外架构思路基于它，但有别于它
